baseURL = "https://weekendcoder.netlify.com/"
canonifyurls = true
defaultContentLanguage = "en-us"
languageCode = "en-us"
paginate = 7
theme = "hugo-tranquilpeak-theme"
title = "The Weekend Coder"
[author]
bio = ""
job = ""
location = "USA"
name = "Jonathan Dent"
picture = "/images/Enlight4.jpg"
twitter = "Jdent022"
[[menu.links]]
identifier = "linkedin"
name = "LinkedIn"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-linkedin\"></i>"
url = "https://www.linkedin.com/in/jonathan-dent-1886409/"
weight = 2
[[menu.links]]
identifier = "github"
name = "GitHub"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
url = "https://github.com/jdent02"
weight = 1
[[menu.main]]
identifier = "about"
name = "About"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
url = "/#about"
weight = 6
[[menu.main]]
identifier = "archives"
name = "Archives"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
url = "/archives"
weight = 5
[[menu.main]]
identifier = "tags"
name = "Tags"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
url = "/tags"
weight = 4
[[menu.main]]
identifier = "categories"
name = "Categories"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
url = "/categories"
weight = 3
[[menu.main]]
identifier = "home"
name = "Home"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
url = "/"
weight = 1
[[menu.main]]
identifier = "projects"
name = "Projects"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-project-diagram\"></i>"
url = "page/blender_plugins"
weight = 2
[[menu.misc]]
identifier = "rss"
name = "RSS"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
url = "/index.xml"
weight = 1
[params]
autoThumbnailImage = true
clearReading = true
coverImage = "abstract-1278077_1920.jpg"
dateFormat = "2 January 2006"
description = "Hugo tranquilpeak theme demo"
hierarchicalCategories = true
imageGallery = true
sidebarBehavior = 1
syntaxHighlighter = "highlight.js"
thumbnailImage = true
thumbnailImagePosition = "bottom"
[params.header.rightLink]
class = ""
icon = ""
url = "/#about"
[[params.sharingOptions]]
icon = "fa-facebook-official"
name = "Facebook"
url = "https://www.facebook.com/sharer/sharer.php?u=%s"
[[params.sharingOptions]]
icon = "fa-twitter"
name = "Twitter"
url = "https://twitter.com/intent/tweet?text=%s"
[permalinks]
post = "/:year/:month/:slug/"
[taxonomies]
archive = "archives"
category = "categories"
tag = "tags"
