baseurl = "https://weekendcoder.netlify.com/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"
title = "So, You Think You Can Blog About Rendering?"
theme = "hamburg"

[params]
    # Short subtitle/tagline. This is displayed in the header.
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
    # To load additional CSS styles
    customCSS = ['hamburg.css']
    # Show this very user-friendly and absolutely not annoying GDPR notice at the bottom of the page
    ShowGDPRNotice = true

[languages]
    [languages.en]
        languageCode = "en"
        languageName = "English"
        subtitle = "A home for musings, thoughts, rants, recipes, general weirdness, and whatever else pops up"
        # Copyright notice. This is displayer in the footer.
        copyright = "&copy; 2019 Jonathan Dent"
        [languages.en.menu]
            [[languages.en.menu.main]]
                name = "About"
                identifier = "about"
                url = "pages/about"
            [[languages.en.menu.main]]
                name = "appleseed"
                identifier = "appleseed"
                url = "pages/appleseed"
            [[languages.en.menu.main]]
                name = "PRMan for Blender"
                identifier = "prmanforblender"
                url = "pages/prmanforblender"
            [[languages.en.menu.main]]
                name = "RIFT Renderer"
                identifier = "rift_renderer"
                url = "pages/rift_renderer"
            [[languages.en.menu.main]]
                name = "RIFT Next"
                identifier = "rift_next"
                url = "pages/rift_next"
    
